CREATE TABLE pauta (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       titulo VARCHAR(200) NOT NULL,
                       descricao TEXT,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);