CREATE TABLE voto (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      pauta_id BIGINT NOT NULL,
                      associado_id VARCHAR(50) NOT NULL,
                      opcao VARCHAR(3) NOT NULL,
                      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT fk_voto_pauta
                          FOREIGN KEY (pauta_id)
                              REFERENCES pauta(id),

                      CONSTRAINT uk_voto_pauta_associado
                          UNIQUE (pauta_id, associado_id),

                      CONSTRAINT ck_voto_opcao
                          CHECK (opcao IN ('SIM', 'NAO'))
);

CREATE INDEX idx_voto_pauta_opcao
    ON voto (pauta_id, opcao);